# Generated by Django 5.2.10 on 2026-01-30 00:54

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0002_2_10'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djstripe.price',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djstripe.product',),
        ),
    ]
